# 파일 경로: .github/workflows/gemini_review.yml

name: Gemini AI Review

# Pull Request가 생성되거나 새로운 커밋이 추가될 때 실행됩니다.
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  # 'review'라는 이름의 작업을 정의합니다.
  review:
    # 최신 우분투 환경에서 실행됩니다.
    runs-on: ubuntu-latest

    # 작업의 단계들을 정의합니다.
    steps:
      # 1. 코드를 체크아웃하는 단계입니다. v4 버전을 사용합니다.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Gemini 액션을 실행하여 리뷰를 수행하는 단계입니다.
      - name: Gemini AI Reviewer
        # 수정된 올바른 액션 이름을 사용합니다.
        uses: google/gemini-action@main
        with:
          # prompt에 원하는 요구사항을 한글로 직접 작성합니다.
          prompt: |
            이 Pull Request는 알고리즘 문제 풀이입니다.
            제출된 코드와 PR 본문을 분석하여, 풀이한 문제와 비슷한 유형의 백준 온라인 저지 문제 3개를 추천해주세요.
            추천 시에는 문제 번호, 제목, 그리고 어떤 점에서 유사한지 간략한 이유를 포함하여 목록 형식으로 작성해주세요.

          # Pull Request에 댓글을 작성하기 위한 GitHub 토큰입니다.
          github_token: ${{ secrets.GITHUB_TOKEN }}thub_token: ${{ secrets.GITHUB_TOKEN }}